### PR TITLE
Added XGBoost Regressor

### PR DESCRIPTION
**Pull request by paulsp94**
## Issue
 * Improve models  #2 
   * Try other models to see if it's possible to improve metrics.

## Fixed
 * Added an XGBoost Regressor with basic tuned parameters.

### CODE REVIEW

**Comment by brunomichetti** [comment]
Thanks for contributing!!!!
Can you add in the README.md, in the part of `Needed libraries`, a new point that saying that you have to install `xgboost`??
A new point in the list with a link to the pypi page of the library and the command to install it. Just as the rest of the points.
Also add the requirement in requirements.txt.
Thanks again!!!!!

**Review by brunomichetti — CHANGES_REQUESTED** [review]
Thanks for contributing!!!!
Can you add in the README.md, in the part of Needed libraries, a new point that saying that you have to install `xgboost`??
A new point in the list with a link to the pypi page of the library and the command to install it. Just as the rest of the points.
Also add the requirement in `requirements.txt.`
Thanks again!!!!!

**Comment by paulsp94** [comment]
I added the xgboost point to the readme. I also added it to the Pipfile, in the project is no requirements.txt should I create one?

**Comment by paulsp94** [comment]
All requested changes fixed.

**Review by brunomichetti — APPROVED** [review]

**Review by mikaelapisani — APPROVED** [review]

**Pull request merged**
